version: "3.8"

services:
  validator:
    image: 'ibn-validator'
    restart: on-failure
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/validator
    environment:
      - COMPOSER_ENV=development

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: documents
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3309:3306"

  web:
    image: 'web-server'
    restart: on-failure
    build:
      context: ./nginx
      dockerfile: Dockerfile
    working_dir: /var/www/
    volumes:
      - .:/var/www/
    env_file:
      - .env
    ports:
      - "8085:8080"
    depends_on:
      - validator
    deploy:
      replicas: 1


volumes:
  mysql-data: {}
